# Generated by Django 3.0 on 2022-01-18 19:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=100.0)),
                ('status', models.CharField(choices=[('PR', 'Under process'), ('DE', 'Delivered'), ('CA', 'Cancelled'), ('RE', 'Received'), ('HO', 'On Hold'), ('ER', 'Error')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_quantity', models.IntegerField(default=0)),
                ('sold', models.IntegerField(blank=True, default=0)),
                ('category_id', models.ManyToManyField(to='inventory.Category')),
            ],
            options={
                'ordering': ['product_name', 'total_quantity'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipment_date', models.DateTimeField(verbose_name='Shipment date')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=100.0)),
                ('payment', models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit Card'), ('DE', 'Debit Card')], max_length=2)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.LineItem')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_address', models.CharField(max_length=200)),
                ('supplier_email', models.EmailField(max_length=200)),
                ('supplier_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('warehouse_location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=1000)),
                ('remain_capacity', models.IntegerField(default=1000)),
                ('product_id', models.ManyToManyField(to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.Shipment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.Shipment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse')),
            ],
        ),
    ]
